### ISSUE TITLE
recursion in ConfiguratioManager

### ISSUE THREAD

**Issue by bluerise** [taigaio/taiga-ncurses#4]
I'm trying to start your program, but I'm hitting this recursion:

```
Traceback (most recent call last):
  File "/Users/patrick/work/github/taiga-ncurses/venv/bin/taiga-ncurses", line 9, in <module>
    load_entry_point('taiga-ncurses==0.0', 'console_scripts', 'taiga-ncurses')()
  File "/Users/patrick/work/github/taiga-ncurses/venv/lib/python3.4/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/patrick/work/github/taiga-ncurses/venv/lib/python3.4/site-packages/pkg_resources.py", line 2302, in load_entry_point
    return ep.load()
  File "/Users/patrick/work/github/taiga-ncurses/venv/lib/python3.4/site-packages/pkg_resources.py", line 2029, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/cli.py", line 9, in <module>
    from taiga_ncurses.core import TaigaCore
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/core.py", line 14, in <module>
    from taiga_ncurses import controllers
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/controllers/__init__.py", line 9, in <module>
    from . import (auth,
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/controllers/projects.py", line 10, in <module>
    from taiga_ncurses.config import settings
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/config.py", line 202, in <module>
    settings = ConfiguratioManager()
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/config.py", line 169, in __init__
    self.data = ConfigData(DEFAULTS.copy())
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/config.py", line 139, in __init__
    self._data = data
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/config.py", line 154, in __setattr__
    self._data[name] = value
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/config.py", line 145, in __getattr__
    if name not in self._data:
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/config.py", line 145, in __getattr__
    if name not in self._data:
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/config.py", line 145, in __getattr__
    if name not in self._data:
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/config.py", line 145, in __getattr__
    if name not in self._data:
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/config.py", line 145, in __getattr__
    if name not in self._data:
  File "/Users/patrick/work/github/taiga-ncurses/taiga_ncurses/config.py", line 145, in __getattr__
    if name not in self._data:
....
RuntimeError: maximum recursion depth exceeded
```

**Comment by banym** [comment]
Would love to see this!

**Comment by bameda** [comment]
Me too, but right now I have no time to dedicate.

I hope to find soon.

**Comment by dumblob** [comment]
This looks awesome! I hope the work on this will continue.

**Comment by victoredwardocallaghan** [comment]
This is awesome! Keep going with it!

**Comment by NikosAlexandris** [comment]
Is this frozen? It simply looks awesome!
