### ISSUE TITLE
Launching taiga-ncurses ends with "ImportError: No module named api.client"

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [taigaio/taiga-ncurses#8]
Hi,
I went through the manual and after typing taiga-ncurses I get exception:
```
(taiga-venv)[kwiat@stokrotka taiga-ncurses]$ taiga-ncurses
Traceback (most recent call last):
  File "/home/kwiat/dev/taiga-ncurses/taiga-venv/bin/taiga-ncurses", line 9, in <module>
    load_entry_point('taiga-ncurses==0.0', 'console_scripts', 'taiga-ncurses')()
  File "/home/kwiat/dev/taiga-ncurses/taiga-venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kwiat/dev/taiga-ncurses/taiga-venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2582, in load_entry_point
    return ep.load()
  File "/home/kwiat/dev/taiga-ncurses/taiga-venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2265, in load
    return self._load()
  File "/home/kwiat/dev/taiga-ncurses/taiga-venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2268, in _load
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kwiat/dev/taiga-ncurses/taiga_ncurses/cli.py", line 8, in <module>
    from taiga_ncurses.api.client import TaigaClient
ImportError: No module named api.client
```

**Comment by bameda** [comment]
@mateuszkwiatkowski you are using python2.7 and taiga-ncurses need python >= 3.3

**Comment by bameda** [comment]
I fix it at https://github.com/taigaio/taiga-ncurses/commit/6a5609dc518897d94d71a3611b890a3364b8917a
